services:
  db:
    container_name: db
    image: mysql:8.4
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    healthcheck:
      test: exit 0
