version: '3'

tasks:
  init:
    cmds:
      - cp apps/api/.env.example apps/api/.env.local
      - cp apps/web-tool/.env.example apps/web-tool/.env.local
  clean:
    cmds:
      - find . -name '.turbo' -type d -prune -exec rm -rf '{}' +
      - find . -name '.next' -type d -prune -exec rm -rf '{}' +
      - find . -name 'dist' -type d -prune -exec rm -rf '{}' +
      - find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
      - find . -name 'pnpm-lock.yaml' -type f -prune -exec rm -rf '{}' +
      - find . -name 'tsconfig.tsbuildinfo' -type f -prune -exec rm -rf '{}' +
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  db:
    cmds:
      - docker compose exec db mysql -u user -p local
  gen:
    dir: apps/api
    cmds:
      - sqlc generate
      - pnpm exec biome check src/gateway/db --apply
