openapi: 3.0.0
info:
  version: 1.0.0
  title: API仕様書
  description: TBD
  contact:
    name: API Support
servers:
  - url: http://localhost:5000
    description: ローカル環境
tags:
  - name: user
paths:
  "/users":
    get:
      operationId: listUsers
      description: list users
      tags:
        - user
      parameters:
        - schema:
            type: string
            format: numeric
            minimum: 1
            maximum: 20
            description: 検索数上限
          required: false
          name: limit
          in: query
        - schema:
            type: string
            format: numeric
            minimum: 0
            maximum: 50
            description: ページネーションのオフセット
          required: false
          name: offset
          in: query
      responses:
        "200":
          description: 正常系
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                required:
                  - name
        "400":
          description: リクエスト異常
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
        "500":
          description: エラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
  "/users/{userId}":
    get:
      operationId: getUserByUserId
      description: get user by user-id
      tags:
        - user
      parameters:
        - schema:
            type: string
            minLength: 1
            maxLength: 8
            description: ユーザーID
          required: true
          name: userId
          in: path
      responses:
        "200":
          description: 正常系
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                required:
                  - name
        "400":
          description: リクエスト異常
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
        "404":
          description: 存在しないユーザー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
        "500":
          description: エラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
components:
  schemas:
    problem:
      type: object
      properties:
        title:
          type: string
          description: 主要なエラーの要因のメッセージ
        type:
          type: string
          description: 呼び出し元APIの定義しているエラーコード
        detail:
          type: string
          description: エラーの詳細に関するメッセージ
        status:
          type: integer
          minimum: 400
          maximum: 600
          description: HTTPステータスコード
          example: 500
      required:
        - title
        - type
        - detail
        - status
      description: Problem Details (RFC 9457)
  parameters: {}
