// 
// Generated by @himenon/openapi-typescript-code-generator v1.0.9
// 
// OpenApi : 3.0.0
// 
// 


import { createRoute, z } from "@hono/zod-openapi";
export const listUsersRoute = createRoute({
    operationId: "listUsers",
    method: "get",
    path: "/users",
    description: "list users",
    request: { query: z.object({ limit: z.string().pipe(z.coerce.number()).optional(), offset: z.string().pipe(z.coerce.number()).optional() }), params: z.object({}), },
    responses: { "200": { description: "\u6B63\u5E38\u7CFB", content: { "application/json": { schema: z.object({ name: z.string() }) } } }, "400": { description: "\u30EA\u30AF\u30A8\u30B9\u30C8\u7570\u5E38", content: { "application/json": { schema: z.object({ title: z.string(), type: z.string(), detail: z.string(), status: z.number().int() }) } } }, "500": { description: "\u30A8\u30E9\u30FC", content: { "application/json": { schema: z.object({ title: z.string(), type: z.string(), detail: z.string(), status: z.number().int() }) } } } },
});
export const getUserByUserIdRoute = createRoute({
    operationId: "getUserByUserId",
    method: "get",
    path: "/users/{userId}",
    description: "get user by user-id",
    request: { query: z.object({}), params: z.object({ userId: z.string() }), },
    responses: { "200": { description: "\u6B63\u5E38\u7CFB", content: { "application/json": { schema: z.object({ name: z.string() }) } } }, "400": { description: "\u30EA\u30AF\u30A8\u30B9\u30C8\u7570\u5E38", content: { "application/json": { schema: z.object({ title: z.string(), type: z.string(), detail: z.string(), status: z.number().int() }) } } }, "404": { description: "\u5B58\u5728\u3057\u306A\u3044\u30E6\u30FC\u30B6\u30FC", content: { "application/json": { schema: z.object({ title: z.string(), type: z.string(), detail: z.string(), status: z.number().int() }) } } }, "500": { description: "\u30A8\u30E9\u30FC", content: { "application/json": { schema: z.object({ title: z.string(), type: z.string(), detail: z.string(), status: z.number().int() }) } } } },
});
